apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-graph
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kub-graph
  template:
    metadata:
      labels:
        app: kub-graph
    spec:
      containers:
      - name: kub-graph
        image: shomos/kub-graph:0.0.4
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kub-graph-svc
spec:
  type: NodePort
  selector:
    app: kub-graph
  ports:
    - port: 80
      targetPort: 3000
