apiVersion: v1
kind: ServiceAccount
metadata:
  name: kub-graph-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kub-graph-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kub-graph-rolebinding
subjects:
  - kind: ServiceAccount
    name: kub-graph-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: kub-graph-role
  apiGroup: rbac.authorization.k8s.io

