name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'  # Срабатывает на любые теги (если нужен определённый формат - например, v*, укажите в этом месте)

  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag for Docker image'
        required: true
        default: 'latest' # Тег по умолчанию

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Это шаг для клонирования репозитория

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Шаг для установки Docker buildx (требуется для некоторых операций)

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Для авторизации с Docker Hub

      - name: Get Git Tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV  # Извлекаем тег из репозитория и сохраняем в переменной

      - name: Build Docker Image
        run: docker build -t shomos/kub-graph:${{ env.TAG }} .  # Сборка образа с тегом из Git

      - name: Push Docker Image
        run: docker push shomos/kub-graph:${{ env.TAG }}  # Отправка в Docker Hub с использованием тега из Git
